// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/components/token-counter.mdx?collection=docs&hash=1740493911843"
import * as docs_5 from "../content/docs/components/thinking-state.mdx?collection=docs&hash=1740493911843"
import * as docs_4 from "../content/docs/components/index.mdx?collection=docs&hash=1740493911843"
import * as docs_3 from "../content/docs/components/ai-parameter-controls.mdx?collection=docs&hash=1740493911843"
import * as docs_2 from "../content/docs/components/ai-feedback-collector.mdx?collection=docs&hash=1740493911843"
import * as docs_1 from "../content/docs/installation.mdx?collection=docs&hash=1740493911843"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1740493911843"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"installation.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/installation.mdx"}, data: docs_1 }, { info: {"path":"components/ai-feedback-collector.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/components/ai-feedback-collector.mdx"}, data: docs_2 }, { info: {"path":"components/ai-parameter-controls.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/components/ai-parameter-controls.mdx"}, data: docs_3 }, { info: {"path":"components/index.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/components/index.mdx"}, data: docs_4 }, { info: {"path":"components/thinking-state.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/components/thinking-state.mdx"}, data: docs_5 }, { info: {"path":"components/token-counter.mdx","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/components/token-counter.mdx"}, data: docs_6 }], [{ info: {"path":"meta.json","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/meta.json"}, data: {"title":"Documentation","pages":["index","installation","components"]} }, { info: {"path":"components/meta.json","absolutePath":"/Users/marcohaber/Documents/nextjs/haberui/content/docs/components/meta.json"}, data: {"pages":["index","ai-feedback-collector","thinking-state","ai-parameter-controls","token-counter"]} }])